<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $form->title }} - Responses</title>
    <style>
        @page { margin: 20mm 15mm; }
        body { font-family: 'Segoe UI', sans-serif; font-size: 10pt; color: #1a1a2e; line-height: 1.5; }
        .header { text-align: center; border-bottom: 2px solid #003778; padding-bottom: 12px; margin-bottom: 20px; }
        .header img { height: 50px; margin-bottom: 6px; }
        .header h1 { font-size: 16pt; color: #003778; margin: 4px 0; }
        .header p { font-size: 9pt; color: #666; margin: 0; }
        .info { margin-bottom: 16px; font-size: 9pt; color: #444; }
        .info strong { color: #003778; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 8.5pt; }
        th { background: #003778; color: #fff; padding: 8px 6px; text-align: left; font-weight: 600; }
        td { padding: 6px; border-bottom: 1px solid #e0e0e0; color: #333; }
        tr:nth-child(even) td { background: #f4f6f9; }
        .footer { position: fixed; bottom: 10mm; left: 0; right: 0; text-align: center; font-size: 7pt; color: #999; border-top: 1px solid #ddd; padding-top: 6px; }
        .page-break { page-break-before: always; }
    </style>
</head>
<body>
    <div class="header">
        <img src="{{ public_path('images/kbb-logo.png') }}" alt="KBB Logo">
        <h1>{{ $form->title }}</h1>
        @if($form->description)
            <p>{{ $form->description }}</p>
        @endif
    </div>

    <div class="info">
        <strong>Total Responses:</strong> {{ $submissions->count() }} |
        <strong>Exported:</strong> {{ now()->format('d M Y H:i') }}
    </div>

    <table>
        <thead>
            <tr>
                <th style="width:32px">#</th>
                <th>Submission UUID</th>
                <th>Submitted At</th>
                @foreach($fields as $field)
                    <th>{{ $field->label }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($submissions as $idx => $submission)
                <tr>
                    <td>{{ $idx + 1 }}</td>
                    <td style="font-family:monospace;font-size:7.5pt">{{ $submission->uuid }}</td>
                    <td>{{ \Carbon\Carbon::parse($submission->submitted_at)->format('d/m/Y H:i') }}</td>
                    @foreach($fields as $field)
                        <td>{{ $submission->data->firstWhere('form_field_id', $field->id)?->value ?? '—' }}</td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by KBB Form — {{ config('app.name') }} | Page {PAGE_NUM}
    </div>
</body>
</html>